In [6]:
import numpy as np
import pandas as pd

## Lec 13 - Data Cleaning - Handle Missing Values

In [12]:
df = pd.read_csv("raw_data.csv")

In [16]:
df.isnull() # Where values is None set as True. 
df.isna()   # it is alias name of the isnull() method.

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [11]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [19]:
df.isnull().sum()  # it is count total values are None in single column. 
# if total 3 values are None in age column it store 3 age column.

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [24]:
df.dropna() # It is a drop row is null value in  row.

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [26]:
# df.dropna(axis=1) # drop a column those have None value in column.

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [28]:
df.fillna(0) # it is fill values where None value avaiable.

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [29]:
df.ffill() # Fill forward values 
# means => in age column "Jane smit" has no age value in age column. "ffill() => method " fill the farward value of "John Doe" age.

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [31]:
df.bfill() # vise varsa like ffill=> forward fill. It start from the backword values.

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## Lec - 14 - Data Cleaning - Handle Duplicates

In [50]:
df.duplicated()
# detected duplicate => gives in True / Flase if it is found duplicate value = True not duplicate => False

0     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [49]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [40]:
df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [48]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [45]:
df2 = df
df2.drop_duplicates(inplace=True)
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## Lec - 15 - Data Cleaning - Handle Data Types

In [47]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [52]:
df.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [76]:
# convert age float64 to int64
df_dtype = df.copy()

# df_dtype = df_dtype["age"]
df_dtype = df_dtype.fillna(0)
df_dtype["age"] = df_dtype["age"].astype("int64").copy()
df_dtype["age"].dtypes

dtype('int64')

In [86]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"])
aqi_data["timestamp"].dtype

dtype('<M8[ns]')

## Lec - 16 Data Cleaning - Handle String

In [88]:
df_str = df.copy()

df_str

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [89]:
df_str["gender"].str.lower()

0        male
2      female
3     unknown
4      female
5        male
6      female
7        male
8      female
9        male
10        NaN
Name: gender, dtype: object

In [90]:
df_str["gender"].str.upper()

0        MALE
2      FEMALE
3     UNKNOWN
4      FEMALE
5        MALE
6      FEMALE
7        MALE
8      FEMALE
9        MALE
10        NaN
Name: gender, dtype: object

In [91]:
df_str["gender"].str.capitalize()

0        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: object

In [94]:
df_str["name"].str.strip() # remove leading and trailing whitespace (spaces, tabs, newlines) from the string values in the "name" column of a DataFrame named df_str.

0         John Doe
2       Jane Smith
3             Alex
4     Maria Garcia
5           Li Wei
6              NaN
7       Ahmed Khan
8       Rachel Lee
9      Carlos Ruiz
10     Emily Davis
Name: name, dtype: object

In [97]:
df_str["name"].str.split(" ")

0         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [98]:
type(df_str["name"].str.split(" ")[0])

list

In [103]:
df_str.columns
df_str["country"].str.contains("US")

0      True
2     False
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10     True
Name: country, dtype: object

In [106]:
df_str["country"].str.contains("india", case=False) 
# india is small case and in Data INDIA is capital. 
# case = False is ignore capital letter ans assuze is small letter and check the vales.

0     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object